workflow:
    - publish

jobs:
    main:
        image: node:6
        steps:
            - install: npm install
            - test: npm test
            # @TODO Remove this when workflow works
            - publish: ./scripts/publish
        secrets:
            - NPM_TOKEN
            - GIT_TOKEN

    publish:
        steps:
            - publish: ./scripts/publish
        secrets:
            - NPM_TOKEN
            - GIT_TOKEN
